name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      env:
        SUPABASE_API_KEY: ${{vars.SUPABASE_API_KEY}}
        SUPABASE_URL_DATABASE: ${{vars.SUPABASE_URL_DATABASE}}
